main:
  - name: About
    url: '#about'
    weight: 1
  - name: Blog
    url: /blog/
    weight: 2
  - name: Projects
    url: /projects/
    weight: 3
  - name: Articles
    url: /docs/
    weight: 4
  - name: Cat Cafe
    url: /cats/
    weight: 5
  - name: Resume
    url: /files/resume.pdf
    weight: 6