main:
  - name: About
    url: '#about'
    weight: 1
  - name: Blog
    url: /blog/
    weight: 2
  - name: Projects
    url: /projects/
    weight: 3
  - name: Book Review
    url: /books/
    weight: 4